name: citizen_issue_reporting
description: Real-Time Citizen Issue Reporting Platform

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Firebase (stable with Dart 3.x)
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7

  # Utilities
  path_provider: ^2.1.2
  image_picker: ^1.2.1
  geolocator: ^10.1.1
  geocoding: ^2.1.1
  connectivity_plus: ^5.0.2
  flutter_web_auth_2: ^5.0.1
  http: ^1.6.0
  url_launcher: ^6.3.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
